### ISSUE TITLE
handlebars files

### ISSUE THREAD

**Issue by roo116** [dolcebasstrombone/jokr#12]

**Comment by josie-franklin** [comment]
Pseudocoded category display in search-jokes.handlbars file on feature/front-end-functionality branch. Won't work until category DB is done and I can make api calls to it.

**Comment by josie-franklin** [comment]
Pseudo coded saved jokes display in dashboard.handlebars file on feature/front-end-functionality branch. Won't work until I can make api calls to find a user's saved jokes.

**Comment by josie-franklin** [comment]
There's an issue in the search page where the event listener is on the whole card, not the button. Will fix tomorrow or after demo, if not done before demo, just don't click the card. Only click the button.

**Comment by josie-franklin** [comment]
closing this to make a more detailed issue.
